#include <iostream>
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#include <openssl/sha.h>
#include <sstream>
#include <iomanip>
#include <torch/torch.h> 
#include "zmq_client.hpp"

std::string get_sha256(void* addr, size_t size) {
    if (!addr) return "NULL_ADDR";
    unsigned char hash[SHA256_DIGEST_LENGTH];
    SHA256((unsigned char*)addr, size, hash);
    std::stringstream ss;
    for(int i = 0; i < SHA256_DIGEST_LENGTH; i++)
        ss << std::hex << std::setw(2) << std::setfill('0') << (int)hash[i];
    return ss.str();
}

int main() {
    // Target the CSV generated by Dev 2's Python script
    const char* filepath = "../python_ml_backend/poison_test.csv"; 
    std::string active_profile = "UPI"; // Switch to "CREDIT" if targeting credit_test.csv

    int fd = open(filepath, O_RDONLY);
    if (fd == -1) {
        std::cerr << "[FATAL] Could not open file: " << filepath << std::endl;
        return 1;
    }

    struct stat sb;
    if (fstat(fd, &sb) == -1) return 1;

    void* addr = mmap(NULL, sb.st_size, PROT_READ, MAP_PRIVATE, fd, 0);
    if (addr == MAP_FAILED) return 1;

    // 1. Provenance Verification
    std::string file_hash = get_sha256(addr, sb.st_size);
    std::cout << "[C++ CORE] Memory Mapped: " << sb.st_size << " bytes.\n";
    std::cout << "[C++ CORE] SHA-256 Verified: " << file_hash << "\n";

    // 2. The Bridge
    ZMQClient client("tcp://127.0.0.1:5555");

    // 3. Zero-Copy Parsing
    std::string content((char*)addr, sb.st_size);
    std::stringstream ss(content);
    std::string line;
    std::getline(ss, line); // Skip Header (feat1,feat2,risk_score)

    int count = 0;
    while (std::getline(ss, line) && count < 50) {
        try {
            std::stringstream line_ss(line);
            std::string val;
            float feat1 = 0, feat2 = 0, label = 0;
            int col = 0;

            while (std::getline(line_ss, val, ',')) {
                if (col == 0) feat1 = std::stof(val);
                if (col == 1) feat2 = std::stof(val);
                if (col == 2) label = std::stof(val);
                col++;
            }

            // Stream to the Python RTX 4070 pipeline
            std::string batch = active_profile + "_TRX_" + std::to_string(count);
            client.send_vector_telemetry(batch, feat1, feat2, label, active_profile);
            count++;
            
            // 0.8s throttle to allow the UI to animate smoothly
            usleep(800000); 
        } catch (...) { continue; }
    }

    munmap(addr, sb.st_size);
    close(fd);
    return 0;
}
